name = input('What is your name? ')
print('Hey', name, end=",")
print(' my name is Asonti! ')
print('Today I will be making a story about you! But first I need you to provide me with 6 things.')
color = input('Provide your favorite color: ')
city = input('Pick any city in the world ')
print(city, 'is a beautiful place.')
game = input('What is your favorite Video Game? ')
money = float(input('Enter a BIG number: '))
age = float(input('How old are you? '))
print('Okay last question')
friend = input('Give me a name of a friend: ')